version: "3"
services:
  web:
    image: harrison/resnet_serving
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1"
          memory: 1000M
      restart_policy:
        condition: on-failure
    ports:
      - "8500:8500"
    networks:
      - webnet
networks:
  webnet:
