version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: oceank/image_prediction_serving:mnist
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1"
          memory: 1000M
      restart_policy:
        condition: on-failure
    ports:
      - "8500:8500"
    networks:
      - webnet
networks:
  webnet:
