networks:
  webnet: null
services:
  web:
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.67'
          memory: 600M
      restart_policy:
        condition: on-failure
    image: oceank/gan-door-number:v1
    networks:
    - webnet
    ports:
    - 8500:8500
version: '3'
